### ISSUE TITLE
Prototoc issue

### ISSUE THREAD

**Issue by hoangtnm** [siamaksalman/denseposeInstalltion#3]
$ make ops
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Caffe2: Found gflags with new-style gflags target.
-- Caffe2: Cannot find glog automatically. Using legacy find.
-- Found glog: /home/hoangtnm/anaconda2/include  
-- Caffe2: Found glog (include: /home/hoangtnm/anaconda2/include, library: /home/hoangtnm/anaconda2/lib/libglog.so)
-- Caffe2: Found protobuf with new-style protobuf targets.
-- Caffe2: Protobuf version 3.5.0
-- Found CUDA: /usr/local/cuda (found suitable version "9.0", minimum required is "7.0") 
-- Caffe2: CUDA detected: 9.0
-- Caffe2: CUDA nvcc is: /usr/local/cuda/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda
-- Caffe2: Header version is: 9.0
-- Found CUDNN: /usr/local/cuda/include  
-- Found cuDNN: v7.1.4  (include: /usr/local/cuda/include, library: /usr/local/cuda/lib64/libcudnn.so)
-- Autodetected CUDA architecture(s): 6.1 
-- Added CUDA NVCC flags for: -gencode;arch=compute_61,code=sm_61
-- Summary:
--   CMake version        : 3.5.1
--   CMake command        : /usr/bin/cmake
--   System name          : Linux
--   C++ compiler         : /usr/bin/c++
--   C++ compiler version : 5.4.0
--   CXX flags            :  -std=c++11 -O2 -fPIC -Wno-narrowing
--   Caffe2 version       : 0.8.2
--   Caffe2 include path  : /home/hoangtnm/anaconda2/include
--   Caffe2 found CUDA    : True
--     CUDA version       : 9.0
--     CuDNN version      : 7.1.4
-- Configuring done
-- Generating done
-- Build files have been written to: /home/hoangtnm/workspace/densepose/build
make[1]: Entering directory '/home/hoangtnm/workspace/densepose/build'
make[2]: Entering directory '/home/hoangtnm/workspace/densepose/build'
make[3]: Entering directory '/home/hoangtnm/workspace/densepose/build'
make[3]: Entering directory '/home/hoangtnm/workspace/densepose/build'
Scanning dependencies of target caffe2_detectron_custom_ops
[ 12%] Building NVCC (Device) object CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/detectron/ops/caffe2_detectron_custom_ops_gpu_generated_zero_even_op.cu.o
[ 25%] Building NVCC (Device) object CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/detectron/ops/caffe2_detectron_custom_ops_gpu_generated_pool_points_interp.cu.o
make[3]: Leaving directory '/home/hoangtnm/workspace/densepose/build'
make[3]: Entering directory '/home/hoangtnm/workspace/densepose/build'
[ 37%] Building CXX object CMakeFiles/caffe2_detectron_custom_ops.dir/detectron/ops/zero_even_op.cc.o
[ 50%] Building CXX object CMakeFiles/caffe2_detectron_custom_ops.dir/detectron/ops/pool_points_interp.cc.o
In file included from /home/hoangtnm/anaconda2/include/caffe2/core/logging.h:12:0,
                 from /home/hoangtnm/anaconda2/include/caffe2/core/allocator.h:6,
                 from /home/hoangtnm/anaconda2/include/caffe2/core/context.h:9,
                 from /home/hoangtnm/workspace/densepose/detectron/ops/zero_even_op.h:12,
                 from /home/hoangtnm/workspace/densepose/detectron/ops/zero_even_op.cc:9:
/home/hoangtnm/anaconda2/include/caffe2/proto/caffe2.pb.h:12:2: error: #error This file was generated by a newer version of protoc which is
 #error This file was generated by a newer version of protoc which is
  ^
/home/hoangtnm/anaconda2/include/caffe2/proto/caffe2.pb.h:13:2: error: #error incompatible with your Protocol Buffer headers. Please update
 #error incompatible with your Protocol Buffer headers.  Please update
  ^
/home/hoangtnm/anaconda2/include/caffe2/proto/caffe2.pb.h:14:2: error: #error your headers.
 #error your headers.
  ^
In file included from /home/hoangtnm/anaconda2/include/caffe2/core/logging.h:12:0,
                 from /home/hoangtnm/anaconda2/include/caffe2/core/allocator.h:6,
                 from /home/hoangtnm/anaconda2/include/caffe2/core/context.h:9,
                 from /home/hoangtnm/workspace/densepose/detectron/ops/pool_points_interp.h:13,
                 from /home/hoangtnm/workspace/densepose/detectron/ops/pool_points_interp.cc:10:
/home/hoangtnm/anaconda2/include/caffe2/proto/caffe2.pb.h:12:2: error: #error This file was generated by a newer version of protoc which is
 #error This file was generated by a newer version of protoc which is
  ^
/home/hoangtnm/anaconda2/include/caffe2/proto/caffe2.pb.h:13:2: error: #error incompatible with your Protocol Buffer headers. Please update
 #error incompatible with your Protocol Buffer headers.  Please update
  ^
/home/hoangtnm/anaconda2/include/caffe2/proto/caffe2.pb.h:14:2: error: #error your headers.
 #error your headers.
  ^
In file included from /home/hoangtnm/anaconda2/include/caffe2/core/logging.h:12:0,
                 from /home/hoangtnm/anaconda2/include/caffe2/core/common_gpu.h:25,
                 from /home/hoangtnm/anaconda2/include/caffe2/core/context_gpu.h:8,
                 from /home/hoangtnm/workspace/densepose/detectron/ops/zero_even_op.cu:9:
/home/hoangtnm/anaconda2/include/caffe2/proto/caffe2.pb.h:12:2: error: #error This file was generated by a newer version of protoc which is
 #error This file was generated by a newer version of protoc which is
  ^
/home/hoangtnm/anaconda2/include/caffe2/proto/caffe2.pb.h:13:2: error: #error incompatible with your Protocol Buffer headers. Please update
 #error incompatible with your Protocol Buffer headers.  Please update
  ^
/home/hoangtnm/anaconda2/include/caffe2/proto/caffe2.pb.h:14:2: error: #error your headers.
 #error your headers.
  ^
In file included from /home/hoangtnm/anaconda2/include/caffe2/core/logging.h:12:0,
                 from /home/hoangtnm/anaconda2/include/caffe2/core/common_gpu.h:25,
                 from /home/hoangtnm/anaconda2/include/caffe2/core/context_gpu.h:8,
                 from /home/hoangtnm/workspace/densepose/detectron/ops/pool_points_interp.cu:11:
/home/hoangtnm/anaconda2/include/caffe2/proto/caffe2.pb.h:12:2: error: #error This file was generated by a newer version of protoc which is
 #error This file was generated by a newer version of protoc which is
  ^
/home/hoangtnm/anaconda2/include/caffe2/proto/caffe2.pb.h:13:2: error: #error incompatible with your Protocol Buffer headers. Please update
 #error incompatible with your Protocol Buffer headers.  Please update
  ^
/home/hoangtnm/anaconda2/include/caffe2/proto/caffe2.pb.h:14:2: error: #error your headers.
 #error your headers.
  ^
CMake Error at caffe2_detectron_custom_ops_gpu_generated_zero_even_op.cu.o.cmake:219 (message):
  Error generating
  /home/hoangtnm/workspace/densepose/build/CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/detectron/ops/./caffe2_detectron_custom_ops_gpu_generated_zero_even_op.cu.o

CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/build.make:63: recipe for target 'CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/detectron/ops/caffe2_detectron_custom_ops_gpu_generated_zero_even_op.cu.o' failed
make[3]: *** [CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/detectron/ops/caffe2_detectron_custom_ops_gpu_generated_zero_even_op.cu.o] Error 1
make[3]: *** Waiting for unfinished jobs....
CMake Error at caffe2_detectron_custom_ops_gpu_generated_pool_points_interp.cu.o.cmake:219 (message):
  Error generating
  /home/hoangtnm/workspace/densepose/build/CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/detectron/ops/./caffe2_detectron_custom_ops_gpu_generated_pool_points_interp.cu.o

CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/build.make:70: recipe for target 'CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/detectron/ops/caffe2_detectron_custom_ops_gpu_generated_pool_points_interp.cu.o' failed
make[3]: *** [CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/detectron/ops/caffe2_detectron_custom_ops_gpu_generated_pool_points_interp.cu.o] Error 1
make[3]: Leaving directory '/home/hoangtnm/workspace/densepose/build'
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/all' failed
make[2]: *** [CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
In file included from /home/hoangtnm/anaconda2/include/caffe2/core/logging.h:12:0,
                 from /home/hoangtnm/anaconda2/include/caffe2/core/allocator.h:6,
                 from /home/hoangtnm/anaconda2/include/caffe2/core/context.h:9,
                 from /home/hoangtnm/workspace/densepose/detectron/ops/zero_even_op.h:12,
                 from /home/hoangtnm/workspace/densepose/detectron/ops/zero_even_op.cc:9:
/home/hoangtnm/anaconda2/include/caffe2/proto/caffe2.pb.h: In member function ‘void caffe2::TensorProto::set_allocated_device_detail(caffe2::DeviceOption*)’:
/home/hoangtnm/anaconda2/include/caffe2/proto/caffe2.pb.h:3405:23: error: ‘GetOwnedMessage’ is not a member of ‘google::protobuf::internal’
       device_detail = ::google::protobuf::internal::GetOwnedMessage(
                       ^
/home/hoangtnm/anaconda2/include/caffe2/proto/caffe2.pb.h: In member function ‘void caffe2::TensorProto::set_allocated_segment(caffe2::TensorProto_Segment*)’:
/home/hoangtnm/anaconda2/include/caffe2/proto/caffe2.pb.h:3459:17: error: ‘GetOwnedMessage’ is not a member of ‘google::protobuf::internal’
       segment = ::google::protobuf::internal::GetOwnedMessage(
                 ^
In file included from /home/hoangtnm/anaconda2/include/caffe2/core/logging.h:12:0,
                 from /home/hoangtnm/anaconda2/include/caffe2/core/allocator.h:6,
                 from /home/hoangtnm/anaconda2/include/caffe2/core/context.h:9,
                 from /home/hoangtnm/workspace/densepose/detectron/ops/pool_points_interp.h:13,
                 from /home/hoangtnm/workspace/densepose/detectron/ops/pool_points_interp.cc:10:
/home/hoangtnm/anaconda2/include/caffe2/proto/caffe2.pb.h: In member function ‘void caffe2::TensorProto::set_allocated_device_detail(caffe2::DeviceOption*)’:
/home/hoangtnm/anaconda2/include/caffe2/proto/caffe2.pb.h:3405:23: error: ‘GetOwnedMessage’ is not a member of ‘google::protobuf::internal’
       device_detail = ::google::protobuf::internal::GetOwnedMessage(
                       ^
/home/hoangtnm/anaconda2/include/caffe2/proto/caffe2.pb.h: In member function ‘void caffe2::TensorProto::set_allocated_segment(caffe2::TensorProto_Segment*)’:
/home/hoangtnm/anaconda2/include/caffe2/proto/caffe2.pb.h:3459:17: error: ‘GetOwnedMessage’ is not a member of ‘google::protobuf::internal’
       segment = ::google::protobuf::internal::GetOwnedMessage(
                 ^
/home/hoangtnm/anaconda2/include/caffe2/proto/caffe2.pb.h: In member function ‘void caffe2::Argument::set_allocated_n(caffe2::NetDef*)’:
/home/hoangtnm/anaconda2/include/caffe2/proto/caffe2.pb.h:4183:11: error: ‘GetOwnedMessage’ is not a member of ‘google::protobuf::internal’
       n = ::google::protobuf::internal::GetOwnedMessage(
           ^
/home/hoangtnm/anaconda2/include/caffe2/proto/caffe2.pb.h: In member function ‘void caffe2::Argument::set_allocated_n(caffe2::NetDef*)’:
/home/hoangtnm/anaconda2/include/caffe2/proto/caffe2.pb.h:4183:11: error: ‘GetOwnedMessage’ is not a member of ‘google::protobuf::internal’
       n = ::google::protobuf::internal::GetOwnedMessage(
           ^
/home/hoangtnm/anaconda2/include/caffe2/proto/caffe2.pb.h: In member function ‘void caffe2::OperatorDef::set_allocated_device_option(caffe2::DeviceOption*)’:
/home/hoangtnm/anaconda2/include/caffe2/proto/caffe2.pb.h:4950:23: error: ‘GetOwnedMessage’ is not a member of ‘google::protobuf::internal’
       device_option = ::google::protobuf::internal::GetOwnedMessage(
                       ^
/home/hoangtnm/anaconda2/include/caffe2/proto/caffe2.pb.h: In member function ‘void caffe2::OperatorDef::set_allocated_device_option(caffe2::DeviceOption*)’:
/home/hoangtnm/anaconda2/include/caffe2/proto/caffe2.pb.h:4950:23: error: ‘GetOwnedMessage’ is not a member of ‘google::protobuf::internal’
       device_option = ::google::protobuf::internal::GetOwnedMessage(
                       ^
/home/hoangtnm/anaconda2/include/caffe2/proto/caffe2.pb.h: In member function ‘void caffe2::NetDef::set_allocated_device_option(caffe2::DeviceOption*)’:
/home/hoangtnm/anaconda2/include/caffe2/proto/caffe2.pb.h:5407:23: error: ‘GetOwnedMessage’ is not a member of ‘google::protobuf::internal’
       device_option = ::google::protobuf::internal::GetOwnedMessage(
                       ^
/home/hoangtnm/anaconda2/include/caffe2/proto/caffe2.pb.h: In member function ‘void caffe2::NetDef::set_allocated_device_option(caffe2::DeviceOption*)’:
/home/hoangtnm/anaconda2/include/caffe2/proto/caffe2.pb.h:5407:23: error: ‘GetOwnedMessage’ is not a member of ‘google::protobuf::internal’
       device_option = ::google::protobuf::internal::GetOwnedMessage(
                       ^
/home/hoangtnm/anaconda2/include/caffe2/proto/caffe2.pb.h: In member function ‘void caffe2::BlobProto::set_allocated_tensor(caffe2::TensorProto*)’:
/home/hoangtnm/anaconda2/include/caffe2/proto/caffe2.pb.h:6409:16: error: ‘GetOwnedMessage’ is not a member of ‘google::protobuf::internal’
       tensor = ::google::protobuf::internal::GetOwnedMessage(
                ^
/home/hoangtnm/anaconda2/include/caffe2/proto/caffe2.pb.h: In member function ‘void caffe2::BlobProto::set_allocated_tensor(caffe2::TensorProto*)’:
/home/hoangtnm/anaconda2/include/caffe2/proto/caffe2.pb.h:6409:16: error: ‘GetOwnedMessage’ is not a member of ‘google::protobuf::internal’
       tensor = ::google::protobuf::internal::GetOwnedMessage(
                ^
/home/hoangtnm/anaconda2/include/caffe2/proto/caffe2.pb.h: In member function ‘void caffe2::BlobProto::set_allocated_qtensor(caffe2::QTensorProto*)’:
/home/hoangtnm/anaconda2/include/caffe2/proto/caffe2.pb.h:6526:17: error: ‘GetOwnedMessage’ is not a member of ‘google::protobuf::internal’
       qtensor = ::google::protobuf::internal::GetOwnedMessage(
                 ^
/home/hoangtnm/anaconda2/include/caffe2/proto/caffe2.pb.h: In member function ‘void caffe2::BlobProto::set_allocated_qtensor(caffe2::QTensorProto*)’:
/home/hoangtnm/anaconda2/include/caffe2/proto/caffe2.pb.h:6526:17: error: ‘GetOwnedMessage’ is not a member of ‘google::protobuf::internal’
       qtensor = ::google::protobuf::internal::GetOwnedMessage(
                 ^
CMakeFiles/caffe2_detectron_custom_ops.dir/build.make:86: recipe for target 'CMakeFiles/caffe2_detectron_custom_ops.dir/detectron/ops/zero_even_op.cc.o' failed
make[3]: *** [CMakeFiles/caffe2_detectron_custom_ops.dir/detectron/ops/zero_even_op.cc.o] Error 1
make[3]: *** Waiting for unfinished jobs....
CMakeFiles/caffe2_detectron_custom_ops.dir/build.make:62: recipe for target 'CMakeFiles/caffe2_detectron_custom_ops.dir/detectron/ops/pool_points_interp.cc.o' failed
make[3]: *** [CMakeFiles/caffe2_detectron_custom_ops.dir/detectron/ops/pool_points_interp.cc.o] Error 1
make[3]: Leaving directory '/home/hoangtnm/workspace/densepose/build'
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/caffe2_detectron_custom_ops.dir/all' failed
make[2]: *** [CMakeFiles/caffe2_detectron_custom_ops.dir/all] Error 2
make[2]: Leaving directory '/home/hoangtnm/workspace/densepose/build'
Makefile:127: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/hoangtnm/workspace/densepose/build'
Makefile:13: recipe for target 'ops' failed
make: *** [ops] Error 2

My system is:
OS: Ubuntu 16.04
GPU: Nvidia GTX 1070Ti
CUDA: 9.0
cuDNN: 7.1.4
Python: 2.7 from anaconda

**Comment by siamaksalman** [comment]
@hoangtnm checkout [this](https://github.com/BVLC/caffe/issues/5645) issue
